In [1]:
import numpy as np
import pandas as pd
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv("54339_104884_bundle_archive/HAM10000_metadata.csv")

In [4]:
data

         lesion_id      image_id     dx dx_type   age     sex localization
0      HAM_0000118  ISIC_0027419    bkl   histo  80.0    male        scalp
1      HAM_0000118  ISIC_0025030    bkl   histo  80.0    male        scalp
2      HAM_0002730  ISIC_0026769    bkl   histo  80.0    male        scalp
3      HAM_0002730  ISIC_0025661    bkl   histo  80.0    male        scalp
4      HAM_0001466  ISIC_0031633    bkl   histo  75.0    male          ear
...            ...           ...    ...     ...   ...     ...          ...
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

[10015 rows x 7 columns]

In [5]:
data.sex = [1 if each == 'female' else 0 for each in data.sex]

In [6]:
data.dx = [1 if each == 'bkl' or each == 'nv' or each == 'df' else 0 for each in data.dx]

In [7]:
data['age'].dropna()

0        80.0
1        80.0
2        80.0
3        80.0
4        75.0
         ...
10010    40.0
10011    40.0
10012    40.0
10013    80.0
10014    70.0
Name: age, Length: 9958, dtype: float64

In [8]:
data = data.dropna()

In [9]:
new_categ = pd.get_dummies(data['localization'],prefix ='local')

In [10]:
new_categ

,local_abdomen,local_acral,local_back,local_chest,local_ear,local_face,local_foot,local_genital,local_hand,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity
0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10010,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10011,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10012,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10013,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
10014,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [11]:
newdf = pd.concat([data,new_categ],axis=1)

In [12]:
newdf.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_face,local_foot,local_genital,local_hand,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
data = newdf

In [14]:
data.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_face,local_foot,local_genital,local_hand,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
new_categ_df = pd.get_dummies(data['dx_type'],prefix ='dx_type')

In [16]:
new_data =  pd.concat([data,new_categ_df],axis=1)

In [17]:
new_data.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [18]:
data = new_data

In [19]:
data.head()

,lesion_id,image_id,dx,dx_type,age,sex,localization,local_abdomen,local_acral,local_back,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
0,HAM_0000118,ISIC_0027419,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,HAM_0000118,ISIC_0025030,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
2,HAM_0002730,ISIC_0026769,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,HAM_0002730,ISIC_0025661,1,histo,80.0,0,scalp,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,HAM_0001466,ISIC_0031633,1,histo,75.0,0,ear,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [20]:
data = data.drop(['localization','lesion_id','image_id','dx_type'],axis=1)

In [21]:
data.head()

,dx,age,sex,local_abdomen,local_acral,local_back,local_chest,local_ear,local_face,local_foot,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
0,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
2,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
3,1,80.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
4,1,75.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [22]:
data.tail()

,dx,age,sex,local_abdomen,local_acral,local_back,local_chest,local_ear,local_face,local_foot,...,local_lower extremity,local_neck,local_scalp,local_trunk,local_unknown,local_upper extremity,dx_type_confocal,dx_type_consensus,dx_type_follow_up,dx_type_histo
10010,0,40.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10011,0,40.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10012,0,40.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10013,0,80.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
10014,0,70.0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [23]:

x = data.drop('dx',axis=1)
y = data['dx']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
mylogmodel = LogisticRegression()

In [28]:
mylogmodel.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
skincancerpredictions = mylogmodel.predict(x_test)

In [30]:
from sklearn.metrics import classification_report

In [31]:
print(classification_report(y_test,skincancerpredictions))

              precision    recall  f1-score   support

           0       0.54      0.41      0.46       632
           1       0.85      0.91      0.88      2356

    accuracy                           0.80      2988
   macro avg       0.70      0.66      0.67      2988
weighted avg       0.79      0.80      0.79      2988

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
accuracy = confusion_matrix(y_test,skincancerpredictions)

In [34]:
accuracy

array([[ 257,  375],
       [ 217, 2139]], dtype=int64)

In [38]:
cm = confusion_matrix(y_test, skincancerpredictions)
confusion = pd.DataFrame(cm, index=['is_cancer', 'is_healthy'],
                         columns=['predicted_cancer','predicted_healthy'])
confusion

            predicted_cancer  predicted_healthy
is_cancer                257                375
is_healthy               217               2139